// Shared by the grip mesh, grounded display pose, and hilt collision.
export const SENBONZAKURA_POMMEL_CENTER_Y=-1.87;
export const SENBONZAKURA_POMMEL_TIP_Y=SENBONZAKURA_POMMEL_CENTER_Y-.10;
export const SENBONZAKURA_GRIP_TOP_Y=-.085;
export const SENBONZAKURA_GRIP_BOTTOM_Y=SENBONZAKURA_POMMEL_CENTER_Y+.04;

export const SENBONZAKURA_BLADE_LENGTH=5.42;
export const SENBONZAKURA_SAYA_LENGTH=SENBONZAKURA_BLADE_LENGTH+.16;
export const SENBONZAKURA_DRAW_DISTANCE=SENBONZAKURA_BLADE_LENGTH+.13;
